/*
    list action for applications
*/
const Actions = {
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  ADMIN_ROUTER_UPDATE: 'ADMIN_ROUTER_UPDATE',
  ADMIN_ROUTER_UPDATE_UPDATE_POST: 'ADMIN_ROUTER_UPDATE_UPDATE_POST',
  POST_DETAIL_VIEW: 'POST_DETAIL_VIEW',
  POST_FILTER_UPDATE: 'POST_FILTER_UPDATE',
  POST_FILTER_RESET: 'POST_FILTER_RESET',
  POST_MANAGE_UPDATE: 'POST_MANAGE_UPDATE',
  POST_FILTER_UPDATE_BLACK_MARKET: 'POST_FILTER_UPDATE_BLACK_MARKET',
  SEARCH_POST_NUM_UPDATE: 'SEARCH_POST_NUM_UPDATE',
  OPEN_MESSAGE_BOX: 'OPEN_MESSAGE_BOX',
  CLOSE_MESSAGE_BOX: 'CLOSE_MESSAGE_BOX',
  RECIVE_MESSAGE: 'RECIVE_MESSAGE',
  RELOAD_USERS_CHAT_HISTORIES: 'RELOAD_USERS_CHAT_HISTORIES',
  MAKE_READ_MESSAGE: 'MAKE_READ_MESSAGE',
  FORK_MESSAGE_USER: 'FORK_MESSAGE_USER',
  RESET_FORK_MESSAGE_USER: 'RESET_FORK_MESSAGE_USER',
}

export default Actions;